### ISSUE TITLE
Error in .bat file with duplicate roms?

### ISSUE THREAD

**Issue by dukesilverfan** [MiSTer-devel/Arcade-MsPacman_MiSTer#1]
I noticed that **build_rom_MsPacman.bat** build file lists 'u5' and 'u7' twice:

`set ifiles=pacman.6e+pacman.6f+pacman.6h+pacman.6j+u5+u5+u6+u7+u7+5e+5f `

I originally assumed this was intentional, but after looking at several other arcade ports, I have not found any other duplicates.

**Comment by sorgelig** [comment]
It is intentional.
Copies aren't used but fill the gap to align the parts.
